trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - script: echo K8's Pipeline
    displayName: 'Run a oneline script'
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'azure_rsa.pub'
  - task: TerraformCLI@0
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes/'
      backendType: 'azurerm'
      backendServiceArm: 'Free Trial(f17664be-6c00-4a53-98ba-ba47d6a803ff)'
      ensureBackend: true
      backendAzureRmResourceGroupName: 'terraform-rg-backend'
      backendAzureRmResourceGroupLocation: 'westeurope'
      backendAzureRmStorageAccountName: 'storageaccountasdfjaklfdjalkwjflksj123'
      backendAzureRmContainerName: 'storageaccountasdfjaklfdjalkwjflksj123container'
      backendAzureRmKey: 'k8s-dev.tfstate'
      allowTelemetryCollection: true